# We install rust ourselves because travis doesn't use rustup yet and that
# prevents installation of the rust-src component.

language: rust
rust:
  - nightly
  
addons:
    apt:
    packages:
      - gcc-arm-none-eabi

script:
  - curl https://sh.rustup.rs -sSf | sh -y
  - /home/travis/.cargo/bin/rustup add component rust-src
  - /home/travis/.cargo/bin/cargo install xargo
  - PATH=/home/travis/.cargo/bin:$PATH ./build.sh
  - PATH=/home/travis/.cargo/bin:$PATH ./build.sh --release
