# We install rust ourselves because travis doesn't use rustup yet and that
# prevents installation of the rust-src component.

sudo: true

os:
  - linux

dist: rusty

cache:
  - apt

addons:
    apt:
      sources:
        - sourceline: 'deb http://archive.ubuntu.com/ubuntu rusty universe'
      packages:
        - gcc-arm-none-eabi

script:
  - ls -lRa /usr/lib/gcc/arm-none-eabi/
  - curl https://sh.rustup.rs -sSf -o rustup.sh
  - chmod +x ./rustup.sh
  - ./rustup.sh -y
  - /home/travis/.cargo/bin/rustup default nightly
  - /home/travis/.cargo/bin/rustup component add rust-src
  - /home/travis/.cargo/bin/cargo install xargo
  - PATH=/home/travis/.cargo/bin:$PATH ./build.sh
  - PATH=/home/travis/.cargo/bin:$PATH ./build.sh --release
